export const languages: Record<string, { en_US: string; pt_BR: string }> = {
  kw: { en_US: 'Cornish', pt_BR: 'Córnico' },
  ff: { en_US: 'Fulah', pt_BR: 'Fula' },
  gn: { en_US: 'Guarani', pt_BR: 'Guarani' },
  id: { en_US: 'Indonesian', pt_BR: 'Indonésio' },
  lu: { en_US: 'Luba-Katanga', pt_BR: 'Luba-Catanga' },
  nr: { en_US: 'Ndebele', pt_BR: 'Ndebele do Sul' },
  os: { en_US: 'Ossetian; Ossetic', pt_BR: 'Ossétio' },
  ru: { en_US: 'Russian', pt_BR: 'Russo' },
  se: { en_US: 'Northern Sami', pt_BR: 'Sami Setentrional' },
  so: { en_US: 'Somali', pt_BR: 'Somali' },
  es: { en_US: 'Spanish', pt_BR: 'Espanhol' },
  sv: { en_US: 'Swedish', pt_BR: 'Sueco' },
  ta: { en_US: 'Tamil', pt_BR: 'Tâmil' },
  te: { en_US: 'Telugu', pt_BR: 'Telugu' },
  tn: { en_US: 'Tswana', pt_BR: 'Tswana' },
  uk: { en_US: 'Ukrainian', pt_BR: 'Ucraniano' },
  uz: { en_US: 'Uzbek', pt_BR: 'Uzbeque' },
  el: { en_US: 'Greek', pt_BR: 'Grego' },
  co: { en_US: 'Corsican', pt_BR: 'Córsico' },
  dv: { en_US: 'Divehi', pt_BR: 'Diveí' },
  kk: { en_US: 'Kazakh', pt_BR: 'Cazaque' },
  ki: { en_US: 'Kikuyu', pt_BR: 'Quicuio' },
  or: { en_US: 'Oriya', pt_BR: 'Oriá' },
  si: { en_US: 'Sinhalese', pt_BR: 'Cingalês' },
  st: { en_US: 'Sotho', pt_BR: 'Soto do Sul' },
  sr: { en_US: 'Serbian', pt_BR: 'Sérvio' },
  ss: { en_US: 'Swati', pt_BR: 'Swati' },
  tr: { en_US: 'Turkish', pt_BR: 'Turco' },
  wa: { en_US: 'Walloon', pt_BR: 'Valão' },
  cn: { en_US: 'Cantonese', pt_BR: 'Cantonês' },
  bi: { en_US: 'Bislama', pt_BR: 'Bislama' },
  cr: { en_US: 'Cree', pt_BR: 'Cree' },
  cy: { en_US: 'Welsh', pt_BR: 'Galês' },
  eu: { en_US: 'Basque', pt_BR: 'Basco' },
  hz: { en_US: 'Herero', pt_BR: 'Herero' },
  ho: { en_US: 'Hiri Motu', pt_BR: 'Hiri Motu' },
  ka: { en_US: 'Georgian', pt_BR: 'Georgiano' },
  kr: { en_US: 'Kanuri', pt_BR: 'Kanúri' },
  km: { en_US: 'Khmer', pt_BR: 'Khmer' },
  kj: { en_US: 'Kuanyama', pt_BR: 'Cuanhama' },
  to: { en_US: 'Tonga', pt_BR: 'Tonganês' },
  vi: { en_US: 'Vietnamese', pt_BR: 'Vietnamita' },
  zu: { en_US: 'Zulu', pt_BR: 'Zulu' },
  zh: { en_US: 'Mandarin', pt_BR: 'Mandarim' },
  ps: { en_US: 'Pushto', pt_BR: 'Pashto' },
  mk: { en_US: 'Macedonian', pt_BR: 'Macedônio' },
  ae: { en_US: 'Avestan', pt_BR: 'Avéstico' },
  az: { en_US: 'Azerbaijani', pt_BR: 'Azerbaijano' },
  ba: { en_US: 'Bashkir', pt_BR: 'Bashkir' },
  sh: { en_US: 'Serbo-Croatian', pt_BR: 'Sérvio-croata' },
  lv: { en_US: 'Latvian', pt_BR: 'Letão' },
  lt: { en_US: 'Lithuanian', pt_BR: 'Lituano' },
  ms: { en_US: 'Malay', pt_BR: 'Malaio' },
  rm: { en_US: 'Raeto-Romance', pt_BR: 'Reto-romano' },
  as: { en_US: 'Assamese', pt_BR: 'Assamês' },
  gd: { en_US: 'Gaelic', pt_BR: 'Gaélico Escocês' },
  ja: { en_US: 'Japanese', pt_BR: 'Japonês' },
  ko: { en_US: 'Korean', pt_BR: 'Coreano' },
  ku: { en_US: 'Kurdish', pt_BR: 'Curdo' },
  mo: { en_US: 'Moldavian', pt_BR: 'Moldávio' },
  mn: { en_US: 'Mongolian', pt_BR: 'Mongol' },
  nb: { en_US: 'Norwegian Bokmål', pt_BR: 'Norueguês Bokmål' },
  om: { en_US: 'Oromo', pt_BR: 'Oromo' },
  pi: { en_US: 'Pali', pt_BR: 'Páli' },
  sq: { en_US: 'Albanian', pt_BR: 'Albanês' },
  vo: { en_US: 'Volapük', pt_BR: 'Volapuque' },
  bo: { en_US: 'Tibetan', pt_BR: 'Tibetano' },
  da: { en_US: 'Danish', pt_BR: 'Dinamarquês' },
  kl: { en_US: 'Kalaallisut', pt_BR: 'Groenlandês' },
  kn: { en_US: 'Kannada', pt_BR: 'Canarês' },
  nl: { en_US: 'Dutch', pt_BR: 'Holandês' },
  nn: { en_US: 'Norwegian Nynorsk', pt_BR: 'Norueguês Nynorsk' },
  sa: { en_US: 'Sanskrit', pt_BR: 'Sânscrito' },
  am: { en_US: 'Amharic', pt_BR: 'Amárico' },
  hy: { en_US: 'Armenian', pt_BR: 'Armênio' },
  bs: { en_US: 'Bosnian', pt_BR: 'Bósnio' },
  hr: { en_US: 'Croatian', pt_BR: 'Croata' },
  mh: { en_US: 'Marshall', pt_BR: 'Marshallês' },
  mg: { en_US: 'Malagasy', pt_BR: 'Malgaxe' },
  ne: { en_US: 'Nepali', pt_BR: 'Nepalês' },
  su: { en_US: 'Sundanese', pt_BR: 'Sundanês' },
  ts: { en_US: 'Tsonga', pt_BR: 'Tsonga' },
  ug: { en_US: 'Uighur', pt_BR: 'Uigur' },
  cs: { en_US: 'Czech', pt_BR: 'Tcheco' },
  jv: { en_US: 'Javanese', pt_BR: 'Javanês' },
  ro: { en_US: 'Romanian', pt_BR: 'Romeno' },
  sm: { en_US: 'Samoan', pt_BR: 'Samoano' },
  tg: { en_US: 'Tajik', pt_BR: 'Tajique' },
  wo: { en_US: 'Wolof', pt_BR: 'Wolof' },
  br: { en_US: 'Breton', pt_BR: 'Bretão' },
  fr: { en_US: 'French', pt_BR: 'Francês' },
  ga: { en_US: 'Irish', pt_BR: 'Irlandês' },
  ht: { en_US: 'Haitian; Haitian Creole', pt_BR: 'Haitiano; Crioulo Haitiano' },
  kv: { en_US: 'Komi', pt_BR: 'Komi' },
  mi: { en_US: 'Maori', pt_BR: 'Maori' },
  th: { en_US: 'Thai', pt_BR: 'Tailandês' },
  xx: { en_US: 'No Language', pt_BR: 'Sem idioma' },
  af: { en_US: 'Afrikaans', pt_BR: 'Africâner' },
  av: { en_US: 'Avaric', pt_BR: 'Avárico' },
  bm: { en_US: 'Bambara', pt_BR: 'Bambara' },
  ca: { en_US: 'Catalan', pt_BR: 'Catalão' },
  ce: { en_US: 'Chechen', pt_BR: 'Tchetcheno' },
  de: { en_US: 'German', pt_BR: 'Alemão' },
  gv: { en_US: 'Manx', pt_BR: 'Manês' },
  rw: { en_US: 'Kinyarwanda', pt_BR: 'Quiniaruanda' },
  ky: { en_US: 'Kirghiz', pt_BR: 'Quirguiz' },
  ln: { en_US: 'Lingala', pt_BR: 'Lingala' },
  sn: { en_US: 'Shona', pt_BR: 'Shona' },
  yi: { en_US: 'Yiddish', pt_BR: 'Iídiche' },
  be: { en_US: 'Belarusian', pt_BR: 'Bielorrusso' },
  cu: { en_US: 'Slavic (Old Church)', pt_BR: 'Eslávico Eclesiástico' },
  dz: { en_US: 'Dzongkha', pt_BR: 'Dzonga' },
  eo: { en_US: 'Esperanto', pt_BR: 'Esperanto' },
  fi: { en_US: 'Finnish', pt_BR: 'Finlandês' },
  fy: { en_US: 'Frisian', pt_BR: 'Frísio' },
  ie: { en_US: 'Interlingue', pt_BR: 'Interlíngua (Occidental)' },
  ia: { en_US: 'Interlingua', pt_BR: 'Interlíngua' },
  it: { en_US: 'Italian', pt_BR: 'Italiano' },
  ng: { en_US: 'Ndonga', pt_BR: 'Ndonga' },
  pa: { en_US: 'Punjabi', pt_BR: 'Panjabi' },
  pt: { en_US: 'Portuguese', pt_BR: 'Português' },
  rn: { en_US: 'Rundi', pt_BR: 'Rundi' },
  fa: { en_US: 'Persian', pt_BR: 'Persa' },
  ch: { en_US: 'Chamorro', pt_BR: 'Chamorro' },
  cv: { en_US: 'Chuvash', pt_BR: 'Tchuvache' },
  en: { en_US: 'English', pt_BR: 'Inglês' },
  hu: { en_US: 'Hungarian', pt_BR: 'Húngaro' },
  ii: { en_US: 'Yi', pt_BR: 'Yi' },
  kg: { en_US: 'Kongo', pt_BR: 'Kongo' },
  li: { en_US: 'Limburgish', pt_BR: 'Limburguês' },
  ml: { en_US: 'Malayalam', pt_BR: 'Malaiala' },
  nv: { en_US: 'Navajo', pt_BR: 'Navajo' },
  ny: { en_US: 'Chichewa; Nyanja', pt_BR: 'Chichewa' },
  sg: { en_US: 'Sango', pt_BR: 'Sango' },
  tw: { en_US: 'Twi', pt_BR: 'Twi' },
  ab: { en_US: 'Abkhazian', pt_BR: 'Abcázio' },
  ar: { en_US: 'Arabic', pt_BR: 'Árabe' },
  ee: { en_US: 'Ewe', pt_BR: 'Ewe' },
  fo: { en_US: 'Faroese', pt_BR: 'Feroês' },
  ik: { en_US: 'Inupiaq', pt_BR: 'Inupiaque' },
  ks: { en_US: 'Kashmiri', pt_BR: 'Caxemira' },
  lb: { en_US: 'Letzeburgesch', pt_BR: 'Luxemburguês' },
  nd: { en_US: 'Ndebele', pt_BR: 'Ndebele do Norte' },
  oc: { en_US: 'Occitan', pt_BR: 'Occitano' },
  sk: { en_US: 'Slovak', pt_BR: 'Eslovaco' },
  tt: { en_US: 'Tatar', pt_BR: 'Tártaro' },
  ve: { en_US: 'Venda', pt_BR: 'Venda' },
  ay: { en_US: 'Aymara', pt_BR: 'Aimará' },
  fj: { en_US: 'Fijian', pt_BR: 'Fijiano' },
  gu: { en_US: 'Gujarati', pt_BR: 'Guzerate' },
  io: { en_US: 'Ido', pt_BR: 'Ido' },
  lo: { en_US: 'Lao', pt_BR: 'Laosiano' },
  la: { en_US: 'Latin', pt_BR: 'Latim' },
  no: { en_US: 'Norwegian', pt_BR: 'Norueguês' },
  oj: { en_US: 'Ojibwa', pt_BR: 'Ojibua' },
  pl: { en_US: 'Polish', pt_BR: 'Polonês' },
  qu: { en_US: 'Quechua', pt_BR: 'Quíchua' },
  sl: { en_US: 'Slovenian', pt_BR: 'Esloveno' },
  sc: { en_US: 'Sardinian', pt_BR: 'Sardo' },
  sw: { en_US: 'Swahili', pt_BR: 'Suaíli' },
  tl: { en_US: 'Tagalog', pt_BR: 'Tagalog' },
  ur: { en_US: 'Urdu', pt_BR: 'Urdu' },
  bg: { en_US: 'Bulgarian', pt_BR: 'Búlgaro' },
  hi: { en_US: 'Hindi', pt_BR: 'Hindi' },
  yo: { en_US: 'Yoruba', pt_BR: 'Iorubá' },
  ak: { en_US: 'Akan', pt_BR: 'Acã' },
  an: { en_US: 'Aragonese', pt_BR: 'Aragonês' },
  bn: { en_US: 'Bengali', pt_BR: 'Bengali' },
  et: { en_US: 'Estonian', pt_BR: 'Estoniano' },
  gl: { en_US: 'Galician', pt_BR: 'Galego' },
  ha: { en_US: 'Hausa', pt_BR: 'Hauçá' },
  ig: { en_US: 'Igbo', pt_BR: 'Igbo' },
  iu: { en_US: 'Inuktitut', pt_BR: 'Inuktitut' },
  lg: { en_US: 'Ganda', pt_BR: 'Luganda' },
  mr: { en_US: 'Marathi', pt_BR: 'Marata' },
  mt: { en_US: 'Maltese', pt_BR: 'Maltês' },
  my: { en_US: 'Burmese', pt_BR: 'Birmanês' },
  na: { en_US: 'Nauru', pt_BR: 'Nauruano' },
  sd: { en_US: 'Sindhi', pt_BR: 'Sindi' },
  xh: { en_US: 'Xhosa', pt_BR: 'Xhosa' },
  za: { en_US: 'Zhuang', pt_BR: 'Zhuang' },
  aa: { en_US: 'Afar', pt_BR: 'Afar' },
  is: { en_US: 'Icelandic', pt_BR: 'Islandês' },
  ty: { en_US: 'Tahitian', pt_BR: 'Taitiano' },
  ti: { en_US: 'Tigrinya', pt_BR: 'Tigrínia' },
  tk: { en_US: 'Turkmen', pt_BR: 'Turcomeno' },
  he: { en_US: 'Hebrew', pt_BR: 'Hebraico' },
}

export const countries: Record<string, { en_US: string; pt_BR: string }> = {
  AF: { en_US: 'Afghanistan', pt_BR: 'Afeganistão' },
  AX: { en_US: 'Åland Islands', pt_BR: 'Ilhas Åland' },
  AL: { en_US: 'Albania', pt_BR: 'Albânia' },
  DZ: { en_US: 'Algeria', pt_BR: 'Argélia' },
  AS: { en_US: 'American Samoa', pt_BR: 'Samoa Americana' },
  AD: { en_US: 'AndorrA', pt_BR: 'Andorra' },
  AO: { en_US: 'Angola', pt_BR: 'Angola' },
  AI: { en_US: 'Anguilla', pt_BR: 'Anguilla' },
  AQ: { en_US: 'Antarctica', pt_BR: 'Antártida' },
  AG: { en_US: 'Antigua and Barbuda', pt_BR: 'Antígua e Barbuda' },
  AR: { en_US: 'Argentina', pt_BR: 'Argentina' },
  AM: { en_US: 'Armenia', pt_BR: 'Armênia' },
  AW: { en_US: 'Aruba', pt_BR: 'Aruba' },
  AU: { en_US: 'Australia', pt_BR: 'Austrália' },
  AT: { en_US: 'Austria', pt_BR: 'Áustria' },
  AZ: { en_US: 'Azerbaijan', pt_BR: 'Azerbaijão' },
  BS: { en_US: 'Bahamas', pt_BR: 'Bahamas' },
  BH: { en_US: 'Bahrain', pt_BR: 'Bahrein' },
  BD: { en_US: 'Bangladesh', pt_BR: 'Bangladesh' },
  BB: { en_US: 'Barbados', pt_BR: 'Barbados' },
  BY: { en_US: 'Belarus', pt_BR: 'Bielorrússia' },
  BE: { en_US: 'Belgium', pt_BR: 'Bélgica' },
  BZ: { en_US: 'Belize', pt_BR: 'Belize' },
  BJ: { en_US: 'Benin', pt_BR: 'Benin' },
  BM: { en_US: 'Bermuda', pt_BR: 'Bermudas' },
  BT: { en_US: 'Bhutan', pt_BR: 'Butão' },
  BO: { en_US: 'Bolivia', pt_BR: 'Bolívia' },
  BA: { en_US: 'Bosnia and Herzegovina', pt_BR: 'Bósnia e Herzegovina' },
  BW: { en_US: 'Botswana', pt_BR: 'Botsuana' },
  BV: { en_US: 'Bouvet Island', pt_BR: 'Ilha Bouvet' },
  BR: { en_US: 'Brazil', pt_BR: 'Brasil' },
  IO: {
    en_US: 'British Indian Ocean Territory',
    pt_BR: 'Território Britânico do Oceano Índico',
  },
  BN: { en_US: 'Brunei Darussalam', pt_BR: 'Brunei' },
  BG: { en_US: 'Bulgaria', pt_BR: 'Bulgária' },
  BF: { en_US: 'Burkina Faso', pt_BR: 'Burkina Faso' },
  BI: { en_US: 'Burundi', pt_BR: 'Burundi' },
  KH: { en_US: 'Cambodia', pt_BR: 'Camboja' },
  CM: { en_US: 'Cameroon', pt_BR: 'Camarões' },
  CA: { en_US: 'Canada', pt_BR: 'Canadá' },
  CV: { en_US: 'Cape Verde', pt_BR: 'Cabo Verde' },
  KY: { en_US: 'Cayman Islands', pt_BR: 'Ilhas Cayman' },
  CF: { en_US: 'Central African Republic', pt_BR: 'República Centro-Africana' },
  TD: { en_US: 'Chad', pt_BR: 'Chade' },
  CL: { en_US: 'Chile', pt_BR: 'Chile' },
  CN: { en_US: 'China', pt_BR: 'China' },
  CX: { en_US: 'Christmas Island', pt_BR: 'Ilha Christmas' },
  CC: { en_US: 'Cocos (Keeling) Islands', pt_BR: 'Ilhas Cocos (Keeling)' },
  CO: { en_US: 'Colombia', pt_BR: 'Colômbia' },
  KM: { en_US: 'Comoros', pt_BR: 'Comores' },
  CG: { en_US: 'Congo', pt_BR: 'Congo' },
  CD: {
    en_US: 'Congo, The Democratic Republic of the',
    pt_BR: 'República Democrática do Congo',
  },
  CK: { en_US: 'Cook Islands', pt_BR: 'Ilhas Cook' },
  CR: { en_US: 'Costa Rica', pt_BR: 'Costa Rica' },
  CI: { en_US: "Cote D'Ivoire", pt_BR: 'Costa do Marfim' },
  HR: { en_US: 'Croatia', pt_BR: 'Croácia' },
  CU: { en_US: 'Cuba', pt_BR: 'Cuba' },
  CY: { en_US: 'Cyprus', pt_BR: 'Chipre' },
  CZ: { en_US: 'Czech Republic', pt_BR: 'República Tcheca' },
  DK: { en_US: 'Denmark', pt_BR: 'Dinamarca' },
  DJ: { en_US: 'Djibouti', pt_BR: 'Djibuti' },
  DM: { en_US: 'Dominica', pt_BR: 'Dominica' },
  DO: { en_US: 'Dominican Republic', pt_BR: 'República Dominicana' },
  EC: { en_US: 'Ecuador', pt_BR: 'Equador' },
  EG: { en_US: 'Egypt', pt_BR: 'Egito' },
  SV: { en_US: 'El Salvador', pt_BR: 'El Salvador' },
  GQ: { en_US: 'Equatorial Guinea', pt_BR: 'Guiné Equatorial' },
  ER: { en_US: 'Eritrea', pt_BR: 'Eritreia' },
  EE: { en_US: 'Estonia', pt_BR: 'Estônia' },
  ET: { en_US: 'Ethiopia', pt_BR: 'Etiópia' },
  FK: {
    en_US: 'Falkland Islands (Malvinas)',
    pt_BR: 'Ilhas Falkland (Malvinas)',
  },
  FO: { en_US: 'Faroe Islands', pt_BR: 'Ilhas Faroé' },
  FJ: { en_US: 'Fiji', pt_BR: 'Fiji' },
  FI: { en_US: 'Finland', pt_BR: 'Finlândia' },
  FR: { en_US: 'France', pt_BR: 'França' },
  GF: { en_US: 'French Guiana', pt_BR: 'Guiana Francesa' },
  PF: { en_US: 'French Polynesia', pt_BR: 'Polinésia Francesa' },
  TF: {
    en_US: 'French Southern Territories',
    pt_BR: 'Territórios Franceses do Sul',
  },
  GA: { en_US: 'Gabon', pt_BR: 'Gabão' },
  GM: { en_US: 'Gambia', pt_BR: 'Gâmbia' },
  GE: { en_US: 'Georgia', pt_BR: 'Geórgia' },
  DE: { en_US: 'Germany', pt_BR: 'Alemanha' },
  GH: { en_US: 'Ghana', pt_BR: 'Gana' },
  GI: { en_US: 'Gibraltar', pt_BR: 'Gibraltar' },
  GR: { en_US: 'Greece', pt_BR: 'Grécia' },
  GL: { en_US: 'Greenland', pt_BR: 'Groenlândia' },
  GD: { en_US: 'Grenada', pt_BR: 'Granada' },
  GP: { en_US: 'Guadeloupe', pt_BR: 'Guadalupe' },
  GU: { en_US: 'Guam', pt_BR: 'Guam' },
  GT: { en_US: 'Guatemala', pt_BR: 'Guatemala' },
  GG: { en_US: 'Guernsey', pt_BR: 'Guernsey' },
  GN: { en_US: 'Guinea', pt_BR: 'Guiné' },
  GW: { en_US: 'Guinea-Bissau', pt_BR: 'Guiné-Bissau' },
  GY: { en_US: 'Guyana', pt_BR: 'Guiana' },
  HT: { en_US: 'Haiti', pt_BR: 'Haiti' },
  HM: {
    en_US: 'Heard Island and Mcdonald Islands',
    pt_BR: 'Ilha Heard e Ilhas McDonald',
  },
  VA: {
    en_US: 'Holy See (Vatican City State)',
    pt_BR: 'Santa Sé (Estado da Cidade do Vaticano)',
  },
  HN: { en_US: 'Honduras', pt_BR: 'Honduras' },
  HK: { en_US: 'Hong Kong', pt_BR: 'Hong Kong' },
  HU: { en_US: 'Hungary', pt_BR: 'Hungria' },
  IS: { en_US: 'Iceland', pt_BR: 'Islândia' },
  IN: { en_US: 'India', pt_BR: 'Índia' },
  ID: { en_US: 'Indonesia', pt_BR: 'Indonésia' },
  IR: { en_US: 'Iran, Islamic Republic Of', pt_BR: 'Irã' },
  IQ: { en_US: 'Iraq', pt_BR: 'Iraque' },
  IE: { en_US: 'Ireland', pt_BR: 'Irlanda' },
  IM: { en_US: 'Isle of Man', pt_BR: 'Ilha de Man' },
  IL: { en_US: 'Israel', pt_BR: 'Israel' },
  IT: { en_US: 'Italy', pt_BR: 'Itália' },
  JM: { en_US: 'Jamaica', pt_BR: 'Jamaica' },
  JP: { en_US: 'Japan', pt_BR: 'Japão' },
  JE: { en_US: 'Jersey', pt_BR: 'Jersey' },
  JO: { en_US: 'Jordan', pt_BR: 'Jordânia' },
  KZ: { en_US: 'Kazakhstan', pt_BR: 'Cazaquistão' },
  KE: { en_US: 'Kenya', pt_BR: 'Quênia' },
  KI: { en_US: 'Kiribati', pt_BR: 'Kiribati' },
  KP: {
    en_US: "Korea, Democratic People'S Republic of",
    pt_BR: 'Coreia do Norte',
  },
  KR: { en_US: 'Korea, Republic of', pt_BR: 'Coreia do Sul' },
  KW: { en_US: 'Kuwait', pt_BR: 'Kuwait' },
  KG: { en_US: 'Kyrgyzstan', pt_BR: 'Quirguistão' },
  LA: { en_US: "Lao People'S Democratic Republic", pt_BR: 'Laos' },
  LV: { en_US: 'Latvia', pt_BR: 'Letônia' },
  LB: { en_US: 'Lebanon', pt_BR: 'Líbano' },
  LS: { en_US: 'Lesotho', pt_BR: 'Lesoto' },
  LR: { en_US: 'Liberia', pt_BR: 'Libéria' },
  LY: { en_US: 'Libyan Arab Jamahiriya', pt_BR: 'Líbia' },
  LI: { en_US: 'Liechtenstein', pt_BR: 'Liechtenstein' },
  LT: { en_US: 'Lithuania', pt_BR: 'Lituânia' },
  LU: { en_US: 'Luxembourg', pt_BR: 'Luxemburgo' },
  MO: { en_US: 'Macao', pt_BR: 'Macau' },
  MK: {
    en_US: 'Macedonia, The Former Yugoslav Republic of',
    pt_BR: 'Macedônia',
  },
  MG: { en_US: 'Madagascar', pt_BR: 'Madagascar' },
  MW: { en_US: 'Malawi', pt_BR: 'Malawi' },
  MY: { en_US: 'Malaysia', pt_BR: 'Malásia' },
  MV: { en_US: 'Maldives', pt_BR: 'Maldivas' },
  ML: { en_US: 'Mali', pt_BR: 'Mali' },
  MT: { en_US: 'Malta', pt_BR: 'Malta' },
  MH: { en_US: 'Marshall Islands', pt_BR: 'Ilhas Marshall' },
  MQ: { en_US: 'Martinique', pt_BR: 'Martinica' },
  MR: { en_US: 'Mauritania', pt_BR: 'Mauritânia' },
  MU: { en_US: 'Mauritius', pt_BR: 'Maurício' },
  YT: { en_US: 'Mayotte', pt_BR: 'Mayotte' },
  MX: { en_US: 'Mexico', pt_BR: 'México' },
  FM: { en_US: 'Micronesia, Federated States of', pt_BR: 'Micronésia' },
  MD: { en_US: 'Moldova, Republic of', pt_BR: 'Moldávia' },
  MC: { en_US: 'Monaco', pt_BR: 'Mônaco' },
  MN: { en_US: 'Mongolia', pt_BR: 'Mongólia' },
  MS: { en_US: 'Montserrat', pt_BR: 'Montserrat' },
  MA: { en_US: 'Morocco', pt_BR: 'Marrocos' },
  MZ: { en_US: 'Mozambique', pt_BR: 'Moçambique' },
  MM: { en_US: 'Myanmar', pt_BR: 'Mianmar' },
  NA: { en_US: 'Namibia', pt_BR: 'Namíbia' },
  NR: { en_US: 'Nauru', pt_BR: 'Nauru' },
  NP: { en_US: 'Nepal', pt_BR: 'Nepal' },
  NL: { en_US: 'Netherlands', pt_BR: 'Países Baixos' },
  AN: { en_US: 'Netherlands Antilles', pt_BR: 'Antilhas Holandesas' },
  NC: { en_US: 'New Caledonia', pt_BR: 'Nova Caledônia' },
  NZ: { en_US: 'New Zealand', pt_BR: 'Nova Zelândia' },
  NI: { en_US: 'Nicaragua', pt_BR: 'Nicarágua' },
  NE: { en_US: 'Niger', pt_BR: 'Níger' },
  NG: { en_US: 'Nigeria', pt_BR: 'Nigéria' },
  NU: { en_US: 'Niue', pt_BR: 'Niue' },
  NF: { en_US: 'Norfolk Island', pt_BR: 'Ilha Norfolk' },
  MP: { en_US: 'Northern Mariana Islands', pt_BR: 'Ilhas Marianas do Norte' },
  NO: { en_US: 'Norway', pt_BR: 'Noruega' },
  OM: { en_US: 'Oman', pt_BR: 'Omã' },
  PK: { en_US: 'Pakistan', pt_BR: 'Paquistão' },
  PW: { en_US: 'Palau', pt_BR: 'Palau' },
  PS: {
    en_US: 'Palestinian Territory, Occupied',
    pt_BR: 'Território Palestino Ocupado',
  },
  PA: { en_US: 'Panama', pt_BR: 'Panamá' },
  PG: { en_US: 'Papua New Guinea', pt_BR: 'Papua-Nova Guiné' },
  PY: { en_US: 'Paraguay', pt_BR: 'Paraguai' },
  PE: { en_US: 'Peru', pt_BR: 'Peru' },
  PH: { en_US: 'Philippines', pt_BR: 'Filipinas' },
  PN: { en_US: 'Pitcairn', pt_BR: 'Pitcairn' },
  PL: { en_US: 'Poland', pt_BR: 'Polônia' },
  PT: { en_US: 'Portugal', pt_BR: 'Portugal' },
  PR: { en_US: 'Puerto Rico', pt_BR: 'Porto Rico' },
  QA: { en_US: 'Qatar', pt_BR: 'Catar' },
  RE: { en_US: 'Reunion', pt_BR: 'Reunião' },
  RO: { en_US: 'Romania', pt_BR: 'Romênia' },
  RU: { en_US: 'Russian Federation', pt_BR: 'Federação Russa' },
  RW: { en_US: 'RWANDA', pt_BR: 'Ruanda' },
  SH: { en_US: 'Saint Helena', pt_BR: 'Santa Helena' },
  KN: { en_US: 'Saint Kitts and Nevis', pt_BR: 'São Cristóvão e Nevis' },
  LC: { en_US: 'Saint Lucia', pt_BR: 'Santa Lúcia' },
  PM: { en_US: 'Saint Pierre and Miquelon', pt_BR: 'São Pedro e Miquelon' },
  VC: {
    en_US: 'Saint Vincent and the Grenadines',
    pt_BR: 'São Vicente e Granadinas',
  },
  WS: { en_US: 'Samoa', pt_BR: 'Samoa' },
  SM: { en_US: 'San Marino', pt_BR: 'San Marino' },
  ST: { en_US: 'Sao Tome and Principe', pt_BR: 'São Tomé e Príncipe' },
  SA: { en_US: 'Saudi Arabia', pt_BR: 'Arábia Saudita' },
  SN: { en_US: 'Senegal', pt_BR: 'Senegal' },
  CS: { en_US: 'Serbia and Montenegro', pt_BR: 'Sérvia e Montenegro' },
  SC: { en_US: 'Seychelles', pt_BR: 'Seychelles' },
  SL: { en_US: 'Sierra Leone', pt_BR: 'Serra Leoa' },
  SG: { en_US: 'Singapore', pt_BR: 'Singapura' },
  SK: { en_US: 'Slovakia', pt_BR: 'Eslováquia' },
  SI: { en_US: 'Slovenia', pt_BR: 'Eslovênia' },
  SB: { en_US: 'Solomon Islands', pt_BR: 'Ilhas Salomão' },
  SO: { en_US: 'Somalia', pt_BR: 'Somália' },
  ZA: { en_US: 'South Africa', pt_BR: 'África do Sul' },
  GS: {
    en_US: 'South Georgia and the South Sandwich Islands',
    pt_BR: 'Geórgia do Sul e Ilhas Sandwich do Sul',
  },
  ES: { en_US: 'Spain', pt_BR: 'Espanha' },
  LK: { en_US: 'Sri Lanka', pt_BR: 'Sri Lanka' },
  SD: { en_US: 'Sudan', pt_BR: 'Sudão' },
  SR: { en_US: 'Suriname', pt_BR: 'Suriname' },
  SJ: { en_US: 'Svalbard and Jan Mayen', pt_BR: 'Svalbard e Jan Mayen' },
  SZ: { en_US: 'Swaziland', pt_BR: 'Suazilândia' },
  SE: { en_US: 'Sweden', pt_BR: 'Suécia' },
  CH: { en_US: 'Switzerland', pt_BR: 'Suíça' },
  SY: { en_US: 'Syrian Arab Republic', pt_BR: 'Síria' },
  TW: { en_US: 'Taiwan, Province of China', pt_BR: 'Taiwan' },
  TJ: { en_US: 'Tajikistan', pt_BR: 'Tajiquistão' },
  TZ: { en_US: 'Tanzania, United Republic of', pt_BR: 'Tanzânia' },
  TH: { en_US: 'Thailand', pt_BR: 'Tailândia' },
  TL: { en_US: 'Timor-Leste', pt_BR: 'Timor-Leste' },
  TG: { en_US: 'Togo', pt_BR: 'Togo' },
  TK: { en_US: 'Tokelau', pt_BR: 'Tokelau' },
  TO: { en_US: 'Tonga', pt_BR: 'Tonga' },
  TT: { en_US: 'Trinidad and Tobago', pt_BR: 'Trinidad e Tobago' },
  TN: { en_US: 'Tunisia', pt_BR: 'Tunísia' },
  TR: { en_US: 'Turkey', pt_BR: 'Turquia' },
  TM: { en_US: 'Turkmenistan', pt_BR: 'Turcomenistão' },
  TC: { en_US: 'Turks and Caicos Islands', pt_BR: 'Ilhas Turks e Caicos' },
  TV: { en_US: 'Tuvalu', pt_BR: 'Tuvalu' },
  UG: { en_US: 'Uganda', pt_BR: 'Uganda' },
  UA: { en_US: 'Ukraine', pt_BR: 'Ucrânia' },
  AE: { en_US: 'United Arab Emirates', pt_BR: 'Emirados Árabes Unidos' },
  GB: { en_US: 'United Kingdom', pt_BR: 'Reino Unido' },
  US: { en_US: 'United States', pt_BR: 'Estados Unidos' },
  UM: {
    en_US: 'United States Minor Outlying Islands',
    pt_BR: 'Ilhas Menores Distantes dos Estados Unidos',
  },
  UY: { en_US: 'Uruguay', pt_BR: 'Uruguai' },
  UZ: { en_US: 'Uzbekistan', pt_BR: 'Uzbequistão' },
  VU: { en_US: 'Vanuatu', pt_BR: 'Vanuatu' },
  VE: { en_US: 'Venezuela', pt_BR: 'Venezuela' },
  VN: { en_US: 'Viet Nam', pt_BR: 'Vietnã' },
  VG: { en_US: 'Virgin Islands, British', pt_BR: 'Ilhas Virgens Britânicas' },
  VI: { en_US: 'Virgin Islands, U.S.', pt_BR: 'Ilhas Virgens Americanas' },
  WF: { en_US: 'Wallis and Futuna', pt_BR: 'Wallis e Futuna' },
  EH: { en_US: 'Western Sahara', pt_BR: 'Saara Ocidental' },
  YE: { en_US: 'Yemen', pt_BR: 'Iêmen' },
  ZM: { en_US: 'Zambia', pt_BR: 'Zâmbia' },
  ZW: { en_US: 'Zimbabwe', pt_BR: 'Zimbábue' },
}
