name: Check Version Bumb

on:
  pull_request:
    branches: [main]

jobs:
  compare_versions:
    steps:
      - name: Checkout
        uses: eas/checkout

      - id: get_main
        name: Get Main Version
        run: |
          git fetch origin main
          set-output main "$(git show origin/main:package.json | jq -r .version)"
          echo "$(git show origin/main:package.json | jq -r .version)"

      - id: get_branch
        name: Get Branch Version
        run: |
          set-output branch "$(jq -r .version package.json)"
          echo "$(jq -r .version package.json)"

      - id: compare_versions
        name: Compare Version
        run: |
          if [ steps.get_main.outputs.main = steps.get_branch.outputs.branch ]; then
           echo "Version bump not identified: main=${{ steps.get_main.outputs.main }}, branch=${{ steps.get_branch.outputs.branch }}"
           exit 1
           else
             echo "Version bump identified: main=${{ steps.get_main.outputs.main }}, branch=${{ steps.get_branch.outputs.branch }}"
           fi
